name: task_organizer
description: A sleek task organizer with calendar, deadlines, and notifications.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.0
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  provider: ^6.1.1
  timezone: ^0.9.2
  intl: ^0.19.0
  uuid: ^4.3.3
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
